# Hikvision NVR Configuration File
# You can define multiple NVRs here

nvrs:
  - ip: "your.nvr.ip.address"
    username: "your_username"
    password: "your_password"
    name: "NVR-1"

# HTTP Server Configuration
server:
  port: "9102"
